FROM nginx:1.27-alpine

COPY frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY frontend/index.html /usr/share/nginx/html/index.html
COPY frontend/config.yaml /usr/share/nginx/html/config.yaml
COPY frontend/js /usr/share/nginx/html/js
